name: ServerRestartPaper
version: '${version}'
main: me.xginko.serverrestart.ServerRestartPaper
authors: [ xGinko ]
description: '${description}'
website: '${url}'
api-version: '1.19'
folia-supported: true
load: POSTWORLD

commands:
  restarts:
    usage: /restarts [ reload, version, disable ]
    description: ServerRestart admin commands
    aliases:
      - sr